version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: go-hexagonal_postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"

volumes:
  postgres:
    driver: local
